title: Devon Zillmer
logo: /profile.png
description: Devon Zillmer, MAJ, USA
show_downloads: true
theme: jekyll-theme-minimal

#remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
